### ISSUE TITLE
closure

### ISSUE THREAD

**Issue by manuel-delverme** [manuel-delverme/constrained_vs_regularized#2]
https://github.com/manuel-delverme/constrained_vs_regularized/blob/e4814185ccb1509cde98d11d3cb5cb7cc65e682a/mnist_classifier.py#L104-L108

Function (loss) evaluation goes inside closure
sampling goes outside

**Comment by nikihowe** [comment]
Ok, I have moved the function evaluation inside the closure, and left the sampling outside
